#pragma author Draxinusom
#pragma description Gold Box Games - Image Enumerations
#pragma once
/***********************
    Image Enums
    Different subsets of the "Picture" type images are available,
    depending on their usage and the module type (Dungeon vs Overland)

    Note:  Animated Sprite image types are never available in Overland modules
***********************/

// 07 - Floor/Ceiling (and Sky) background images - BACK.TLB
enum IMG_07_FLOORCEILING:u8 {
    NoArt = 0,
    StoneFloor = 1,
    Marble = 2,
    Cave = 3,
    Forest = 4,
    Coral = 5,
    Lava = 6,
    Adobe = 7,
    Wood = 8,
    Bricks = 9,
    FireBricks = 10,
    FireBricksHole = 11,
    Swamp = 12,
    TreasureChest = 13,
    DarkCoral = 14,
    Wasteland = 15,
    Black = 17,
    OutdoorGrass = 32,
    OutdoorMud = 34,
    NotApplicable = 255
};

// 07 - Wall images - 8X8D[BC].TLB
enum IMG_07_WALL:u8 {
    NoArt = 0,
    Rock_A = 1,
    Rock_B = 2,
    Adobe = 3,
    Webs = 5,
    Bricks = 6,
    Cave = 7,
    Wood_A = 8,
    Wood_B = 9,
    Wasteland = 10,
    Marble = 11,
    Trees_A = 12,
    Coral_A = 13,
    Coral_B = 14,
    Lava = 15,
    FireBricks = 16,
    Trees_B = 17,
    NotApplicable = 255
};

// 10 - Floor/Ceiling (and Sky) background images - Dungeon modules only - BACK.TLB
enum IMG_10_FLOORCEILING:u8 {
    NoArt = 0,
    StoneFloor = 1,
    Marble = 2,
    Cave = 3,
    Forest = 4,
    Coral = 5,
    Lava = 6,
    Adobe = 7,
    Wood = 8,
    Bricks = 9,
    FireBricks = 10,
    Swamp = 11,
    DarkCoral = 12,
    Wasteland = 13,
    OutdoorGrass = 32,
    OutdoorMud = 34,
    OutdoorStone = 36,
    NotApplicable = 255
};

// 10 - Wall images - Dungeon modules only - 8X8D[BC].TLB
enum IMG_10_WALL:u8 {
    NoArt = 0,
    Rock_A = 1,
    Rock_B = 2,
    Adobe = 3,
    Webs = 4,
    Bricks = 5,
    Cave = 6,
    Wood_A = 7,
    Wood_B = 8,
    Wasteland = 9,
    Marble = 10,
    Trees_A = 11,
    Trees_B = 12,
    Coral_A = 13,
    Coral_B = 14,
    Lava = 15,
    FireBricks = 16,
    NotApplicable = 255
};

// Indoors combat background tiles - Dungeon modules only - DUNGCOM.TLB
enum IMG_COMBAT_IN:u8 {
    NoArt = 0,
    Rock = 1,
    Cave = 2,
    Coral = 3,
    Adobe = 4,
    Lava = 5,
    NotApplicable = 255
};

// Outdoors combat background tiles - Dungeon & Overland modules - WILDCOM.TLB
enum IMG_COMBAT_OUT:u8 {
    NoArt = 0,
    River = 1,
    Forest = 2,
    Swamp = 3,
    Wasteland = 4,
    NotApplicable = 255
};

// All "picture" & animated sprite type images - Dungeon modules only - BIGPI[CX].TLB / PIC[A-F].TLB / SPRIT.TLB
// Note:  Included commented out lines of monsters without a picture for informational purposes
enum IMG_PIC_ALL:u8 {
    NoArt = 0,
    Kobold = 1,             // Monster 54 - Sprite
    Goblin = 2,             // Monster 45 - Small
    Orc = 3,                // Monster 68 - Small
    Hobgoblin = 4,          // Monster 50 - Small
    //OrcChieftain = 5,     // Monster 69 - None
    //HobgoblinChief = 6,   // Monster 51 - None
    Gnoll = 7,              // Monster 44 - Small
    Ogre = 8,               // Monster 65 - Small
    Troll = 9,              // Monster 90 - Small
    HillGiant = 10,         // Monster 39 - Sprite
    FireGiant = 11,         // Monster 37 - Sprite
    //FrostGiant = 12,      // Monster 38 - None
    CloudGiant = 13,        // Monster 36 - Sprite
    //StormGiant = 14,      // Monster 41 - None
    //GiantRat = 15,        // Monster 43 - None
    CarrionCrawler = 16,    // Monster 8 - Small
    EnormousSpider = 17,    // Monster 83 - Small
    //Skeleton = 18,        // Monster 79 - None
    Zombie = 19,            // Monster 102 - Sprite
    Ghoul = 20,             // Monster 35 - Small
    //Ghast = 21,           // Monster 34 - None
    Wight = 22,             // Monster 98 - Sprite
    //Wraith = 23,          // Monster 99 - None
    //Mummy = 24,           // Monster 64 - None
    Spectre = 25,           // Monster 82 - Sprite
    Vampire = 26,           // Monster 92 - Small
    Lich = 27,              // Monster 55 - Small
    LizardMan = 28,         // Monster 58 - Small
    //LizardManKing = 29,   // Monster 59 - None
    Minotaur = 30,          // Monster 62 - Small
    //DisplacerBeast = 31,  // Monster 10 - None
    BoringBeetle = 32,      // Monster 2 - Sprite
    Griffon = 33,           // Monster 48 - Small
    Hydra = 34,             // Monster 52 - Small
    //Wyvern = 35,          // Monster 101 - None
    BlackDragon = 36,       // Monster 15 - Sprite
    BlueDragon = 37,        // Monster 16 - Sprite
    GreenDragon = 38,       // Monster 17 - Sprite
    RedDragon = 39,         // Monster 18 - Small
    WhiteDragon = 40,       // Monster 21 - Sprite
    Dracolich = 41,         // Monster 12 - Small
    Basilisk = 42,          // Monster 1 - Sprite
    Gorgon = 43,            // Monster 47 - Sprite
    //Cockatrice = 44,      // Monster 9 - None
    Beholder = 45,          // Monster 3 - Sprite
    OgreMage = 46,          // Monster 66 - Small
    Bulette = 47,           // Monster 7 - Small
    ShamblingMound = 48,    // Monster 78 - Sprite
    Margoyle = 49,          // Monster 60 - Small
    //Dracolisk = 50,       // Monster 13 - None
    Mobat = 51,             // Monster 63 - Sprite
    BlackPudding = 52,      // Monster 5 - Sprite
    Otyugh = 53,            // Monster 70 - Sprite
    //NeoOtyugh = 54,       // Monster 71 - None
    Salamander = 55,        // Monster 77 - Sprite
    //Efreeti = 56,         // Monster 29 - None
    EarthElemental = 57,    // Monster 30 - Small
    FireElemental = 58,     // Monster 31 - Small
    UmberHulk = 59,         // Monster 91 - Sprite
    Ettin = 60,             // Monster 32 - Sprite
    //Owlbear = 61,         // Monster 72 - None
    //Bugbear = 62,         // Monster 6 - None
    Medusa = 63,            // Monster 61 - Sprite
    GiantSpider = 64,       // Monster 84 - Sprite
    //PhaseSpider = 65,     // Monster 85 - None
    PoisonousSnake = 66,    // Monster 73 - Sprite
    HellHound = 67,         // Monster 49 - Small
    //GiantCrocodile = 68,  // Monster 42 - None
    Drider = 69,            // Monster 22 - Sprite
    IronGolem = 70,         // Monster 53 - Small
    Rakshasa = 71,          // Monster 75 - Small
    PurpleWorm = 72,        // Monster 74 - Sprite
    DrowChampion = 73,      // Monster 24 - Small
    //DrowPriest = 74,      // Monster 25 - None
    DrowSorceress = 75,     // Monster 27 - Small
    //DrowPriestess = 76,   // Monster 26 - None
    Warrior = 77,           // Fighters 37 - Sprite
    //Conjurer = 78,        // Mages 1 - None
    //Acolyte = 79,         // Clerics 3 - None
    Goon = 80,              // Thieves 5 - Small
    Archer = 81,            // Fighters 12 - Small
    Theurgist = 82,         // Mages 13 - Sprite
    //Priest = 83,          // Clerics 9 - None
    //Thug = 84,            // Thieves 11 - None
    EvilChampion = 85,      // Fighters 24 - Sprite
    Magician = 86,          // Mages 6 - Sprite
    DarkCleric = 87,        // Clerics 5 - Small
    Rogue = 88,             // Thieves 8 - Small
    DarkKnight = 89,        // Fighters 19 - Sprite
    Necromancer = 90,       // Mages 12 - Sprite
    HighPriest = 91,        // Clerics 8 - Sprite
    Thief = 92,             // Thieves 10 - Small
    DarkWarlord = 93,       // Fighters 22 - Sprite
    Wizard = 94,            // Mages 14 - Small
    //Archpriest = 95,      // Clerics 4 - None
    MasterThief = 96,       // Thieves 7 - Sprite
    //DarkOverlord = 97,    // Fighters 21 - None
    MasterWizard = 98,      // Mages 10 - Small
    //DarkDisciple = 99,    // Clerics 6 - None
    HighThief = 100,        // Thieves 6 - Sprite
    VampireLord = 101,      // Monster 93 - Small
    Vampiress = 102,        // Monster 95 - Small
    Dazmilar = 103,         // Thieves 4 - Small
    //OgreShaman = 104,     // Monster 67 - None
    SirDutiocs = 105,       // Fighters 33 - Small
    Vidruand = 106,         // Monster 96 - Small
    //HillGtShaman = 107,   // Monster 40 - None
    //VampirePriest = 108,  // Monster 94 - None
    DrowAmazon = 109,       // Monster 23 - Small
    //RakshasaRukh = 110,   // Monster 76 - None
    //RoadGuard = 111,      // Fighters 32 - None
    Kallithrea = 112,       // Clerics 1 - Small
    Yemandra = 113,         // Fighters 11 - Small
    //Krondasz = 114,       // Fighters 28 - None
    //Arderiel = 115,       // Fighters 13 - None
    //Tornilee = 116,       // Fighters 8 - None
    Alias = 117,            // Fighters 1 - Small
    Dragonbait = 118,       // Fighters 23 - Small
    Nacacia = 119,          // Thieves 1 - Small
    Priam = 120,            // Fighters 31 - Small
    Vala = 121,             // Fighters 9 - Small
    Silk = 122,             // Thieves 3 - Small
    CaptainDaenor = 123,    // Fighters 17 - Small
    Grunschka = 124,        // Fighters 3 - Small
    //Storm = 125,          // Fighters 36 - None
    Shal = 126,             // Fighters 6 - Small
    //Raizel = 127,         // Thieves 2 - None
    Camp2 = 128,            // Camps 2 - Small
    Treasure1 = 129,        // Treasures 1 - Small
    Camp1 = 130,            // Camps 1 - Small
    Treasure2 = 131,        // Treasures 2 - Small
    Tower4 = 132,           // Towers 4 - Small
    Baldric = 133,          // Characters 8 - Small
    Bartender = 134,        // Townspeople 2 - Small
    BitOMoander = 135,      // Monster 4 - Small
    Bjorn = 136,            // Fighters 16 - Small
    Gatekeeper = 137,       // Townspeople 5 - Small
    Town3 = 138,            // Towns 3 - Small
    Town2 = 139,            // Towns 2 - Small
    Town1 = 140,            // Towns 1 - Small
    Crysia = 141,           // Characters 1 - Small
    Ring = 142,             // Items 8 - Small
    LichAndBride = 143,     // Monster 56 - Small
    Ship3 = 144,            // Ships 3 - Small
    Morudel = 145,          // Characters 14 - Small
    DragonDuel = 146,       // Combats 1 - Small
    LichNoble = 147,        // Monster 57 - Small
    SeaDragon = 148,        // Monster 20 - Small
    SirFtucis = 149,        // Fighters 34 - Small
    LunitBdufe = 150,       // Clerics 2 - Small
    DrowToDrider = 151,     // Monster 28 - Small
    DwarfPriest = 152,      // Clerics 7 - Small
    Elastul = 153,          // Characters 2 - Small
    Elea = 154,             // Characters 3 - Small
    Elminster = 155,        // Mages 2 - Small
    EshallaTheHag = 156,    // Characters 4 - Small
    Eshalla = 157,          // Characters 5 - Small
    Ezra = 158,             // Characters 10 - Small
    Fastillion = 159,       // Mages 3 - Small
    Fatman = 160,           // Characters 11 - Small
    SadDragon = 161,        // Monster 19 - Small
    Gateway1 = 162,         // Portals 1 - Small
    Gauhok = 163,           // Fighters 25 - Small
    Maiden = 164,           // Townspeople 7 - Small
    Mage = 165,             // Mages 5 - Small
    Gheildar = 166,         // Mages 4 - Small
    DwarfKing = 167,        // Characters 9 - Small
    TanarriBalor = 168,     // Monster 86 - Small
    Barbarian = 169,        // Fighters 15 - Small
    Horn = 170,             // Items 6 - Small
    Icehunt = 171,          // Fighters 26 - Small
    Innkeeper = 172,        // Townspeople 6 - Small
    IronWall2 = 173,        // Eldritch Realms 3 - Small
    Jabarkas = 174,         // Fighters 27 - Small
    Jagaerda = 175,         // Fighters 4 - Small
    TanarriMari = 176,      // Monster 88 - Small
    MoonshaeRoyals = 177,   // Characters 13 - Small
    Limbo = 178,            // Eldritch Realms 4 - Small
    Tower3 = 179,           // Towers 3 - Small
    Lyzian = 180,           // Characters 12 - Small
    Malchor = 181,          // Mages 8 - Small
    Marcus = 182,           // Mages 9 - Small
    EvilSpirit = 183,       // Monster 33 - Small
    Amulet = 184,           // Items 1 - Small
    Northman = 185,         // Fighters 30 - Small
    Figurine = 186,         // Items 4 - Small
    Town4 = 187,            // Towns 4 - Small
    Wand = 188,             // Items 11 - Small
    Book = 189,             // Items 3 - Small
    Orb = 190,              // Items 7 - Small
    Rolf = 191,             // Characters 15 - Small
    Ship2 = 192,            // Ships 2 - Small
    Sasha = 193,            // Characters 7 - Small
    MaisonThorvald = 194,   // Mages 7 - Small
    Sapphire = 195,         // Characters 6 - Small
    GoblinKing = 196,       // Monster 46 - Small
    Hammer = 197,           // Items 5 - Small
    DarkSwordsman = 198,    // Fighters 20 - Small
    Watchwoman = 199,       // Fighters 10 - Small
    Jovena = 200,           // Fighters 5 - Small
    SkeletonHorde = 201,    // Monster 80 - Small
    Fejyelsae = 202,        // Fighters 2 - Small
    TheSearchers = 203,     // Characters 17 - Small
    Mordenkainen = 204,     // Mages 11 - Small
    Mardus = 205,           // Fighters 29 - Small
    TanarriNalf = 206,      // Monster 89 - Small
    Tower2 = 207,           // Towers 2 - Small
    Selias = 208,           // Thieves 9 - Small
    Ship1 = 209,            // Ships 1 - Small
    Shopkeeper = 210,       // Townspeople 8 - Small
    Crone = 211,            // Townspeople 3 - Small
    Blade = 212,            // Items 2 - Small
    Scroll = 213,           // Items 9 - Small
    Steelfist = 214,        // Fighters 35 - Small
    CurioDealer = 215,      // Townspeople 4 - Small
    Sulajia = 216,          // Fighters 7 - Small
    Talisman = 217,         // Items 10 - Small
    Barmaid = 218,          // Townspeople 1 - Small
    Gateway2 = 219,         // Portals 2 - Small
    TemplePriest = 220,     // Clerics 10 - Small
    GatewayDoom = 221,      // Portals 3 - Small
    SpectralMinion = 222,   // Monster 81 - Small
    ChaoticWarrior = 223,   // Fighters 18 - Small
    AncientDragon = 224,    // Monster 14 - Small
    Tower1 = 225,           // Towers 1 - Small
    ArmsMaster = 226,       // Fighters 14 - Small
    IronWall = 227,         // Eldritch Realms 2 - Small
    TanarriGlab = 228,      // Monster 87 - Small
    SeaElf = 229,           // Characters 16 - Small
    Dolphin = 230,          // Monster 11 - Small
    Camp3 = 231,            // Camps 3 - Small
    WesternCormyr = 240,    // Maps 5 - Map
    MoonseaRealms = 241,    // Maps 1 - Map
    WebRealm = 242,         // Maps 4 - Map
    SouthernKsoh = 243,     // Maps 2 - Map
    WhiteWyrm = 244,        // Monster 100 - Big
    WalkingForest = 245,    // Monster 97 - Big
    PhlanDeluge = 246,      // Eldritch Realms 5 - Big
    DreadGate = 247,        // Eldritch Realms 1 - Big
    SorceryDuel = 248,      // Combats 3 - Big
    SwordVsStaff = 249,     // Combats 4 - Big
    Tower5 = 250,           // Towers 5 - Big
    MaydayGold1 = 251,      // Combats 2 - Big
    TheDalelands = 252      // Maps 3 - Map
};

// Maps pics only -Overland modules only - BIGPI[CX].TLB
enum IMG_PIC_MAP:u8 {
    NoArt = 0,
    WesternCormyr = 240,    // Maps 5 - Map
    MoonseaRealms = 241,    // Maps 1 - Map
    WebRealm = 242,         // Maps 4 - Map
    SouthernKsoh = 243,     // Maps 2 - Map
    TheDalelands = 252      // Maps 3 - Map
};

// All pictures without animated sprites - Overland modules only - BIGPI[CX].TLB / PIC[A-F].TLB
enum IMG_PIC_NOSPRITE:u8 {
    NoArt = 0,
    Goblin = 2,             // Monster 45 - Small
    Orc = 3,                // Monster 68 - Small
    Hobgoblin = 4,          // Monster 50 - Small
    Gnoll = 7,              // Monster 44 - Small
    Ogre = 8,               // Monster 65 - Small
    Troll = 9,              // Monster 90 - Small
    CarrionCrawler = 16,    // Monster 8 - Small
    EnormousSpider = 17,    // Monster 83 - Small
    Ghoul = 20,             // Monster 35 - Small
    Vampire = 26,           // Monster 92 - Small
    Lich = 27,              // Monster 55 - Small
    LizardMan = 28,         // Monster 58 - Small
    Minotaur = 30,          // Monster 62 - Small
    Griffon = 33,           // Monster 48 - Small
    Hydra = 34,             // Monster 52 - Small
    RedDragon = 39,         // Monster 18 - Small
    Dracolich = 41,         // Monster 12 - Small
    OgreMage = 46,          // Monster 66 - Small
    Bulette = 47,           // Monster 7 - Small
    Margoyle = 49,          // Monster 60 - Small
    EarthElemental = 57,    // Monster 30 - Small
    FireElemental = 58,     // Monster 31 - Small
    HellHound = 67,         // Monster 49 - Small
    IronGolem = 70,         // Monster 53 - Small
    Rakshasa = 71,          // Monster 75 - Small
    DrowChampion = 73,      // Monster 24 - Small
    DrowSorceress = 75,     // Monster 27 - Small
    Goon = 80,              // Thieves 5 - Small
    Archer = 81,            // Fighters 12 - Small
    DarkCleric = 87,        // Clerics 5 - Small
    Rogue = 88,             // Thieves 8 - Small
    Thief = 92,             // Thieves 10 - Small
    Wizard = 94,            // Mages 14 - Small
    MasterWizard = 98,      // Mages 10 - Small
    VampireLord = 101,      // Monster 93 - Small
    Vampiress = 102,        // Monster 95 - Small
    Dazmilar = 103,         // Thieves 4 - Small
    SirDutiocs = 105,       // Fighters 33 - Small
    Vidruand = 106,         // Monster 96 - Small
    DrowAmazon = 109,       // Monster 23 - Small
    Kallithrea = 112,       // Clerics 1 - Small
    Yemandra = 113,         // Fighters 11 - Small
    Alias = 117,            // Fighters 1 - Small
    Dragonbait = 118,       // Fighters 23 - Small
    Nacacia = 119,          // Thieves 1 - Small
    Priam = 120,            // Fighters 31 - Small
    Vala = 121,             // Fighters 9 - Small
    Silk = 122,             // Thieves 3 - Small
    CaptainDaenor = 123,    // Fighters 17 - Small
    Grunschka = 124,        // Fighters 3 - Small
    Shal = 126,             // Fighters 6 - Small
    Camp2 = 128,            // Camps 2 - Small
    Treasure1 = 129,        // Treasures 1 - Small
    Camp1 = 130,            // Camps 1 - Small
    Treasure2 = 131,        // Treasures 2 - Small
    Tower4 = 132,           // Towers 4 - Small
    Baldric = 133,          // Characters 8 - Small
    Bartender = 134,        // Townspeople 2 - Small
    BitOMoander = 135,      // Monster 4 - Small
    Bjorn = 136,            // Fighters 16 - Small
    Gatekeeper = 137,       // Townspeople 5 - Small
    Town3 = 138,            // Towns 3 - Small
    Town2 = 139,            // Towns 2 - Small
    Town1 = 140,            // Towns 1 - Small
    Crysia = 141,           // Characters 1 - Small
    Ring = 142,             // Items 8 - Small
    LichAndBride = 143,     // Monster 56 - Small
    Ship3 = 144,            // Ships 3 - Small
    Morudel = 145,          // Characters 14 - Small
    DragonDuel = 146,       // Combats 1 - Small
    LichNoble = 147,        // Monster 57 - Small
    SeaDragon = 148,        // Monster 20 - Small
    SirFtucis = 149,        // Fighters 34 - Small
    LunitBdufe = 150,       // Clerics 2 - Small
    DrowToDrider = 151,     // Monster 28 - Small
    DwarfPriest = 152,      // Clerics 7 - Small
    Elastul = 153,          // Characters 2 - Small
    Elea = 154,             // Characters 3 - Small
    Elminster = 155,        // Mages 2 - Small
    EshallaTheHag = 156,    // Characters 4 - Small
    Eshalla = 157,          // Characters 5 - Small
    Ezra = 158,             // Characters 10 - Small
    Fastillion = 159,       // Mages 3 - Small
    Fatman = 160,           // Characters 11 - Small
    SadDragon = 161,        // Monster 19 - Small
    Gateway1 = 162,         // Portals 1 - Small
    Gauhok = 163,           // Fighters 25 - Small
    Maiden = 164,           // Townspeople 7 - Small
    Mage = 165,             // Mages 5 - Small
    Gheildar = 166,         // Mages 4 - Small
    DwarfKing = 167,        // Characters 9 - Small
    TanarriBalor = 168,     // Monster 86 - Small
    Barbarian = 169,        // Fighters 15 - Small
    Horn = 170,             // Items 6 - Small
    Icehunt = 171,          // Fighters 26 - Small
    Innkeeper = 172,        // Townspeople 6 - Small
    IronWall2 = 173,        // Eldritch Realms 3 - Small
    Jabarkas = 174,         // Fighters 27 - Small
    Jagaerda = 175,         // Fighters 4 - Small
    TanarriMari = 176,      // Monster 88 - Small
    MoonshaeRoyals = 177,   // Characters 13 - Small
    Limbo = 178,            // Eldritch Realms 4 - Small
    Tower3 = 179,           // Towers 3 - Small
    Lyzian = 180,           // Characters 12 - Small
    Malchor = 181,          // Mages 8 - Small
    Marcus = 182,           // Mages 9 - Small
    EvilSpirit = 183,       // Monster 33 - Small
    Amulet = 184,           // Items 1 - Small
    Northman = 185,         // Fighters 30 - Small
    Figurine = 186,         // Items 4 - Small
    Town4 = 187,            // Towns 4 - Small
    Wand = 188,             // Items 11 - Small
    Book = 189,             // Items 3 - Small
    Orb = 190,              // Items 7 - Small
    Rolf = 191,             // Characters 15 - Small
    Ship2 = 192,            // Ships 2 - Small
    Sasha = 193,            // Characters 7 - Small
    MaisonThorvald = 194,   // Mages 7 - Small
    Sapphire = 195,         // Characters 6 - Small
    GoblinKing = 196,       // Monster 46 - Small
    Hammer = 197,           // Items 5 - Small
    DarkSwordsman = 198,    // Fighters 20 - Small
    Watchwoman = 199,       // Fighters 10 - Small
    Jovena = 200,           // Fighters 5 - Small
    SkeletonHorde = 201,    // Monster 80 - Small
    Fejyelsae = 202,        // Fighters 2 - Small
    TheSearchers = 203,     // Characters 17 - Small
    Mordenkainen = 204,     // Mages 11 - Small
    Mardus = 205,           // Fighters 29 - Small
    TanarriNalf = 206,      // Monster 89 - Small
    Tower2 = 207,           // Towers 2 - Small
    Selias = 208,           // Thieves 9 - Small
    Ship1 = 209,            // Ships 1 - Small
    Shopkeeper = 210,       // Townspeople 8 - Small
    Crone = 211,            // Townspeople 3 - Small
    Blade = 212,            // Items 2 - Small
    Scroll = 213,           // Items 9 - Small
    Steelfist = 214,        // Fighters 35 - Small
    CurioDealer = 215,      // Townspeople 4 - Small
    Sulajia = 216,          // Fighters 7 - Small
    Talisman = 217,         // Items 10 - Small
    Barmaid = 218,          // Townspeople 1 - Small
    Gateway2 = 219,         // Portals 2 - Small
    TemplePriest = 220,     // Clerics 10 - Small
    GatewayDoom = 221,      // Portals 3 - Small
    SpectralMinion = 222,   // Monster 81 - Small
    ChaoticWarrior = 223,   // Fighters 18 - Small
    AncientDragon = 224,    // Monster 14 - Small
    Tower1 = 225,           // Towers 1 - Small
    ArmsMaster = 226,       // Fighters 14 - Small
    IronWall = 227,         // Eldritch Realms 2 - Small
    TanarriGlab = 228,      // Monster 87 - Small
    SeaElf = 229,           // Characters 16 - Small
    Dolphin = 230,          // Monster 11 - Small
    Camp3 = 231,            // Camps 3 - Small
    WesternCormyr = 240,    // Maps 5 - Map
    MoonseaRealms = 241,    // Maps 1 - Map
    WebRealm = 242,         // Maps 4 - Map
    SouthernKsoh = 243,     // Maps 2 - Map
    WhiteWyrm = 244,        // Monster 100 - Big
    WalkingForest = 245,    // Monster 97 - Big
    PhlanDeluge = 246,      // Eldritch Realms 5 - Big
    DreadGate = 247,        // Eldritch Realms 1 - Big
    SorceryDuel = 248,      // Combats 3 - Big
    SwordVsStaff = 249,     // Combats 4 - Big
    Tower5 = 250,           // Towers 5 - Big
    MaydayGold1 = 251,      // Combats 2 - Big
    TheDalelands = 252      // Maps 3 - Map
};

// Small pictures - Dungeon & Overland modules - PIC[A-F].TLB
enum IMG_PIC_SMALL:u8 {
    NoArt = 0,
    Goblin = 2,             // Monster 45 - Small
    Orc = 3,                // Monster 68 - Small
    Hobgoblin = 4,          // Monster 50 - Small
    Gnoll = 7,              // Monster 44 - Small
    Ogre = 8,               // Monster 65 - Small
    Troll = 9,              // Monster 90 - Small
    CarrionCrawler = 16,    // Monster 8 - Small
    EnormousSpider = 17,    // Monster 83 - Small
    Ghoul = 20,             // Monster 35 - Small
    Vampire = 26,           // Monster 92 - Small
    Lich = 27,              // Monster 55 - Small
    LizardMan = 28,         // Monster 58 - Small
    Minotaur = 30,          // Monster 62 - Small
    Griffon = 33,           // Monster 48 - Small
    Hydra = 34,             // Monster 52 - Small
    RedDragon = 39,         // Monster 18 - Small
    Dracolich = 41,         // Monster 12 - Small
    OgreMage = 46,          // Monster 66 - Small
    Bulette = 47,           // Monster 7 - Small
    Margoyle = 49,          // Monster 60 - Small
    EarthElemental = 57,    // Monster 30 - Small
    FireElemental = 58,     // Monster 31 - Small
    HellHound = 67,         // Monster 49 - Small
    IronGolem = 70,         // Monster 53 - Small
    Rakshasa = 71,          // Monster 75 - Small
    DrowChampion = 73,      // Monster 24 - Small
    DrowSorceress = 75,     // Monster 27 - Small
    Goon = 80,              // Thieves 5 - Small
    Archer = 81,            // Fighters 12 - Small
    DarkCleric = 87,        // Clerics 5 - Small
    Rogue = 88,             // Thieves 8 - Small
    Thief = 92,             // Thieves 10 - Small
    Wizard = 94,            // Mages 14 - Small
    MasterWizard = 98,      // Mages 10 - Small
    VampireLord = 101,      // Monster 93 - Small
    Vampiress = 102,        // Monster 95 - Small
    Dazmilar = 103,         // Thieves 4 - Small
    SirDutiocs = 105,       // Fighters 33 - Small
    Vidruand = 106,         // Monster 96 - Small
    DrowAmazon = 109,       // Monster 23 - Small
    Kallithrea = 112,       // Clerics 1 - Small
    Yemandra = 113,         // Fighters 11 - Small
    Alias = 117,            // Fighters 1 - Small
    Dragonbait = 118,       // Fighters 23 - Small
    Nacacia = 119,          // Thieves 1 - Small
    Priam = 120,            // Fighters 31 - Small
    Vala = 121,             // Fighters 9 - Small
    Silk = 122,             // Thieves 3 - Small
    CaptainDaenor = 123,    // Fighters 17 - Small
    Grunschka = 124,        // Fighters 3 - Small
    Shal = 126,             // Fighters 6 - Small
    Camp2 = 128,            // Camps 2 - Small
    Treasure1 = 129,        // Treasures 1 - Small
    Camp1 = 130,            // Camps 1 - Small
    Treasure2 = 131,        // Treasures 2 - Small
    Tower4 = 132,           // Towers 4 - Small
    Baldric = 133,          // Characters 8 - Small
    Bartender = 134,        // Townspeople 2 - Small
    BitOMoander = 135,      // Monster 4 - Small
    Bjorn = 136,            // Fighters 16 - Small
    Gatekeeper = 137,       // Townspeople 5 - Small
    Town3 = 138,            // Towns 3 - Small
    Town2 = 139,            // Towns 2 - Small
    Town1 = 140,            // Towns 1 - Small
    Crysia = 141,           // Characters 1 - Small
    Ring = 142,             // Items 8 - Small
    LichAndBride = 143,     // Monster 56 - Small
    Ship3 = 144,            // Ships 3 - Small
    Morudel = 145,          // Characters 14 - Small
    DragonDuel = 146,       // Combats 1 - Small
    LichNoble = 147,        // Monster 57 - Small
    SeaDragon = 148,        // Monster 20 - Small
    SirFtucis = 149,        // Fighters 34 - Small
    LunitBdufe = 150,       // Clerics 2 - Small
    DrowToDrider = 151,     // Monster 28 - Small
    DwarfPriest = 152,      // Clerics 7 - Small
    Elastul = 153,          // Characters 2 - Small
    Elea = 154,             // Characters 3 - Small
    Elminster = 155,        // Mages 2 - Small
    EshallaTheHag = 156,    // Characters 4 - Small
    Eshalla = 157,          // Characters 5 - Small
    Ezra = 158,             // Characters 10 - Small
    Fastillion = 159,       // Mages 3 - Small
    Fatman = 160,           // Characters 11 - Small
    SadDragon = 161,        // Monster 19 - Small
    Gateway1 = 162,         // Portals 1 - Small
    Gauhok = 163,           // Fighters 25 - Small
    Maiden = 164,           // Townspeople 7 - Small
    Mage = 165,             // Mages 5 - Small
    Gheildar = 166,         // Mages 4 - Small
    DwarfKing = 167,        // Characters 9 - Small
    TanarriBalor = 168,     // Monster 86 - Small
    Barbarian = 169,        // Fighters 15 - Small
    Horn = 170,             // Items 6 - Small
    Icehunt = 171,          // Fighters 26 - Small
    Innkeeper = 172,        // Townspeople 6 - Small
    IronWall2 = 173,        // Eldritch Realms 3 - Small
    Jabarkas = 174,         // Fighters 27 - Small
    Jagaerda = 175,         // Fighters 4 - Small
    TanarriMari = 176,      // Monster 88 - Small
    MoonshaeRoyals = 177,   // Characters 13 - Small
    Limbo = 178,            // Eldritch Realms 4 - Small
    Tower3 = 179,           // Towers 3 - Small
    Lyzian = 180,           // Characters 12 - Small
    Malchor = 181,          // Mages 8 - Small
    Marcus = 182,           // Mages 9 - Small
    EvilSpirit = 183,       // Monster 33 - Small
    Amulet = 184,           // Items 1 - Small
    Northman = 185,         // Fighters 30 - Small
    Figurine = 186,         // Items 4 - Small
    Town4 = 187,            // Towns 4 - Small
    Wand = 188,             // Items 11 - Small
    Book = 189,             // Items 3 - Small
    Orb = 190,              // Items 7 - Small
    Rolf = 191,             // Characters 15 - Small
    Ship2 = 192,            // Ships 2 - Small
    Sasha = 193,            // Characters 7 - Small
    MaisonThorvald = 194,   // Mages 7 - Small
    Sapphire = 195,         // Characters 6 - Small
    GoblinKing = 196,       // Monster 46 - Small
    Hammer = 197,           // Items 5 - Small
    DarkSwordsman = 198,    // Fighters 20 - Small
    Watchwoman = 199,       // Fighters 10 - Small
    Jovena = 200,           // Fighters 5 - Small
    SkeletonHorde = 201,    // Monster 80 - Small
    Fejyelsae = 202,        // Fighters 2 - Small
    TheSearchers = 203,     // Characters 17 - Small
    Mordenkainen = 204,     // Mages 11 - Small
    Mardus = 205,           // Fighters 29 - Small
    TanarriNalf = 206,      // Monster 89 - Small
    Tower2 = 207,           // Towers 2 - Small
    Selias = 208,           // Thieves 9 - Small
    Ship1 = 209,            // Ships 1 - Small
    Shopkeeper = 210,       // Townspeople 8 - Small
    Crone = 211,            // Townspeople 3 - Small
    Blade = 212,            // Items 2 - Small
    Scroll = 213,           // Items 9 - Small
    Steelfist = 214,        // Fighters 35 - Small
    CurioDealer = 215,      // Townspeople 4 - Small
    Sulajia = 216,          // Fighters 7 - Small
    Talisman = 217,         // Items 10 - Small
    Barmaid = 218,          // Townspeople 1 - Small
    Gateway2 = 219,         // Portals 2 - Small
    TemplePriest = 220,     // Clerics 10 - Small
    GatewayDoom = 221,      // Portals 3 - Small
    SpectralMinion = 222,   // Monster 81 - Small
    ChaoticWarrior = 223,   // Fighters 18 - Small
    AncientDragon = 224,    // Monster 14 - Small
    Tower1 = 225,           // Towers 1 - Small
    ArmsMaster = 226,       // Fighters 14 - Small
    IronWall = 227,         // Eldritch Realms 2 - Small
    TanarriGlab = 228,      // Monster 87 - Small
    SeaElf = 229,           // Characters 16 - Small
    Dolphin = 230,          // Monster 11 - Small
    Camp3 = 231,            // Camps 3 - Small
};

// Small pictures and animated sprites - Dungeon modules only - PIC[A-F].TLB - SPRIT.TLB
enum IMG_PIC_SMALLSPRITE:u8 {
    NoArt = 0,
    Kobold = 1,             // Monster 54 - Sprite
    Goblin = 2,             // Monster 45 - Small
    Orc = 3,                // Monster 68 - Small
    Hobgoblin = 4,          // Monster 50 - Small
    Gnoll = 7,              // Monster 44 - Small
    Ogre = 8,               // Monster 65 - Small
    Troll = 9,              // Monster 90 - Small
    HillGiant = 10,         // Monster 39 - Sprite
    FireGiant = 11,         // Monster 37 - Sprite
    CloudGiant = 13,        // Monster 36 - Sprite
    CarrionCrawler = 16,    // Monster 8 - Small
    EnormousSpider = 17,    // Monster 83 - Small
    Zombie = 19,            // Monster 102 - Sprite
    Ghoul = 20,             // Monster 35 - Small
    Wight = 22,             // Monster 98 - Sprite
    Spectre = 25,           // Monster 82 - Sprite
    Vampire = 26,           // Monster 92 - Small
    Lich = 27,              // Monster 55 - Small
    LizardMan = 28,         // Monster 58 - Small
    Minotaur = 30,          // Monster 62 - Small
    BoringBeetle = 32,      // Monster 2 - Sprite
    Griffon = 33,           // Monster 48 - Small
    Hydra = 34,             // Monster 52 - Small
    BlackDragon = 36,       // Monster 15 - Sprite
    BlueDragon = 37,        // Monster 16 - Sprite
    GreenDragon = 38,       // Monster 17 - Sprite
    RedDragon = 39,         // Monster 18 - Small
    WhiteDragon = 40,       // Monster 21 - Sprite
    Dracolich = 41,         // Monster 12 - Small
    Basilisk = 42,          // Monster 1 - Sprite
    Gorgon = 43,            // Monster 47 - Sprite
    Beholder = 45,          // Monster 3 - Sprite
    OgreMage = 46,          // Monster 66 - Small
    Bulette = 47,           // Monster 7 - Small
    ShamblingMound = 48,    // Monster 78 - Sprite
    Margoyle = 49,          // Monster 60 - Small
    Mobat = 51,             // Monster 63 - Sprite
    BlackPudding = 52,      // Monster 5 - Sprite
    Otyugh = 53,            // Monster 70 - Sprite
    Salamander = 55,        // Monster 77 - Sprite
    EarthElemental = 57,    // Monster 30 - Small
    FireElemental = 58,     // Monster 31 - Small
    UmberHulk = 59,         // Monster 91 - Sprite
    Ettin = 60,             // Monster 32 - Sprite
    Medusa = 63,            // Monster 61 - Sprite
    GiantSpider = 64,       // Monster 84 - Sprite
    PoisonousSnake = 66,    // Monster 73 - Sprite
    HellHound = 67,         // Monster 49 - Small
    Drider = 69,            // Monster 22 - Sprite
    IronGolem = 70,         // Monster 53 - Small
    Rakshasa = 71,          // Monster 75 - Small
    PurpleWorm = 72,        // Monster 74 - Sprite
    DrowChampion = 73,      // Monster 24 - Small
    DrowSorceress = 75,     // Monster 27 - Small
    Warrior = 77,           // Fighters 37 - Sprite
    Goon = 80,              // Thieves 5 - Small
    Archer = 81,            // Fighters 12 - Small
    Theurgist = 82,         // Mages 13 - Sprite
    EvilChampion = 85,      // Fighters 24 - Sprite
    Magician = 86,          // Mages 6 - Sprite
    DarkCleric = 87,        // Clerics 5 - Small
    Rogue = 88,             // Thieves 8 - Small
    DarkKnight = 89,        // Fighters 19 - Sprite
    Necromancer = 90,       // Mages 12 - Sprite
    HighPriest = 91,        // Clerics 8 - Sprite
    Thief = 92,             // Thieves 10 - Small
    DarkWarlord = 93,       // Fighters 22 - Sprite
    Wizard = 94,            // Mages 14 - Small
    MasterThief = 96,       // Thieves 7 - Sprite
    MasterWizard = 98,      // Mages 10 - Small
    HighThief = 100,        // Thieves 6 - Sprite
    VampireLord = 101,      // Monster 93 - Small
    Vampiress = 102,        // Monster 95 - Small
    Dazmilar = 103,         // Thieves 4 - Small
    SirDutiocs = 105,       // Fighters 33 - Small
    Vidruand = 106,         // Monster 96 - Small
    DrowAmazon = 109,       // Monster 23 - Small
    Kallithrea = 112,       // Clerics 1 - Small
    Yemandra = 113,         // Fighters 11 - Small
    Alias = 117,            // Fighters 1 - Small
    Dragonbait = 118,       // Fighters 23 - Small
    Nacacia = 119,          // Thieves 1 - Small
    Priam = 120,            // Fighters 31 - Small
    Vala = 121,             // Fighters 9 - Small
    Silk = 122,             // Thieves 3 - Small
    CaptainDaenor = 123,    // Fighters 17 - Small
    Grunschka = 124,        // Fighters 3 - Small
    Shal = 126,             // Fighters 6 - Small
    Camp2 = 128,            // Camps 2 - Small
    Treasure1 = 129,        // Treasures 1 - Small
    Camp1 = 130,            // Camps 1 - Small
    Treasure2 = 131,        // Treasures 2 - Small
    Tower4 = 132,           // Towers 4 - Small
    Baldric = 133,          // Characters 8 - Small
    Bartender = 134,        // Townspeople 2 - Small
    BitOMoander = 135,      // Monster 4 - Small
    Bjorn = 136,            // Fighters 16 - Small
    Gatekeeper = 137,       // Townspeople 5 - Small
    Town3 = 138,            // Towns 3 - Small
    Town2 = 139,            // Towns 2 - Small
    Town1 = 140,            // Towns 1 - Small
    Crysia = 141,           // Characters 1 - Small
    Ring = 142,             // Items 8 - Small
    LichAndBride = 143,     // Monster 56 - Small
    Ship3 = 144,            // Ships 3 - Small
    Morudel = 145,          // Characters 14 - Small
    DragonDuel = 146,       // Combats 1 - Small
    LichNoble = 147,        // Monster 57 - Small
    SeaDragon = 148,        // Monster 20 - Small
    SirFtucis = 149,        // Fighters 34 - Small
    LunitBdufe = 150,       // Clerics 2 - Small
    DrowToDrider = 151,     // Monster 28 - Small
    DwarfPriest = 152,      // Clerics 7 - Small
    Elastul = 153,          // Characters 2 - Small
    Elea = 154,             // Characters 3 - Small
    Elminster = 155,        // Mages 2 - Small
    EshallaTheHag = 156,    // Characters 4 - Small
    Eshalla = 157,          // Characters 5 - Small
    Ezra = 158,             // Characters 10 - Small
    Fastillion = 159,       // Mages 3 - Small
    Fatman = 160,           // Characters 11 - Small
    SadDragon = 161,        // Monster 19 - Small
    Gateway1 = 162,         // Portals 1 - Small
    Gauhok = 163,           // Fighters 25 - Small
    Maiden = 164,           // Townspeople 7 - Small
    Mage = 165,             // Mages 5 - Small
    Gheildar = 166,         // Mages 4 - Small
    DwarfKing = 167,        // Characters 9 - Small
    TanarriBalor = 168,     // Monster 86 - Small
    Barbarian = 169,        // Fighters 15 - Small
    Horn = 170,             // Items 6 - Small
    Icehunt = 171,          // Fighters 26 - Small
    Innkeeper = 172,        // Townspeople 6 - Small
    IronWall2 = 173,        // Eldritch Realms 3 - Small
    Jabarkas = 174,         // Fighters 27 - Small
    Jagaerda = 175,         // Fighters 4 - Small
    TanarriMari = 176,      // Monster 88 - Small
    MoonshaeRoyals = 177,   // Characters 13 - Small
    Limbo = 178,            // Eldritch Realms 4 - Small
    Tower3 = 179,           // Towers 3 - Small
    Lyzian = 180,           // Characters 12 - Small
    Malchor = 181,          // Mages 8 - Small
    Marcus = 182,           // Mages 9 - Small
    EvilSpirit = 183,       // Monster 33 - Small
    Amulet = 184,           // Items 1 - Small
    Northman = 185,         // Fighters 30 - Small
    Figurine = 186,         // Items 4 - Small
    Town4 = 187,            // Towns 4 - Small
    Wand = 188,             // Items 11 - Small
    Book = 189,             // Items 3 - Small
    Orb = 190,              // Items 7 - Small
    Rolf = 191,             // Characters 15 - Small
    Ship2 = 192,            // Ships 2 - Small
    Sasha = 193,            // Characters 7 - Small
    MaisonThorvald = 194,   // Mages 7 - Small
    Sapphire = 195,         // Characters 6 - Small
    GoblinKing = 196,       // Monster 46 - Small
    Hammer = 197,           // Items 5 - Small
    DarkSwordsman = 198,    // Fighters 20 - Small
    Watchwoman = 199,       // Fighters 10 - Small
    Jovena = 200,           // Fighters 5 - Small
    SkeletonHorde = 201,    // Monster 80 - Small
    Fejyelsae = 202,        // Fighters 2 - Small
    TheSearchers = 203,     // Characters 17 - Small
    Mordenkainen = 204,     // Mages 11 - Small
    Mardus = 205,           // Fighters 29 - Small
    TanarriNalf = 206,      // Monster 89 - Small
    Tower2 = 207,           // Towers 2 - Small
    Selias = 208,           // Thieves 9 - Small
    Ship1 = 209,            // Ships 1 - Small
    Shopkeeper = 210,       // Townspeople 8 - Small
    Crone = 211,            // Townspeople 3 - Small
    Blade = 212,            // Items 2 - Small
    Scroll = 213,           // Items 9 - Small
    Steelfist = 214,        // Fighters 35 - Small
    CurioDealer = 215,      // Townspeople 4 - Small
    Sulajia = 216,          // Fighters 7 - Small
    Talisman = 217,         // Items 10 - Small
    Barmaid = 218,          // Townspeople 1 - Small
    Gateway2 = 219,         // Portals 2 - Small
    TemplePriest = 220,     // Clerics 10 - Small
    GatewayDoom = 221,      // Portals 3 - Small
    SpectralMinion = 222,   // Monster 81 - Small
    ChaoticWarrior = 223,   // Fighters 18 - Small
    AncientDragon = 224,    // Monster 14 - Small
    Tower1 = 225,           // Towers 1 - Small
    ArmsMaster = 226,       // Fighters 14 - Small
    IronWall = 227,         // Eldritch Realms 2 - Small
    TanarriGlab = 228,      // Monster 87 - Small
    SeaElf = 229,           // Characters 16 - Small
    Dolphin = 230,          // Monster 11 - Small
    Camp3 = 231             // Camps 3 - Small
};
